jtype: VggishAudioEncoder
with:
  {}
metas:
  py_modules:
    - vggish/mel_features.py
    - vggish/vggish_input.py
    - vggish/vggish_params.py
    - vggish/vggish_postprocess.py
    - vggish/vggish_slim.py
    - vggish_audio_encoder.py

