name: CI

on: [pull_request]

jobs:
  hub-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Soundfile
        run: |
          sudo apt-get install libsndfile1
      - id: tests
        run: ./scripts/tests.sh